#!/usr/bin/env bash

alert() {
  notify-send --urgency=low "Plasisent" "$@"
}


sass src/styles/master.scss > static/assets/styles/master.css

nanoc && alert "Build completed" || alert "Build failed"

